### PR TITLE
kube-proxy ipvs implementation

### PR DESCRIPTION
**Pull request by dujun1990**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by dujun1990** [comment]
Initial implementation for kube-proxy ipvs mode. Passed basic functional cases.

**Comment by dhilipkumars** [comment]
@dujun1990 

Here is my Initial code review feedback.  
**proxier.go**
I have only one biggest concern is that we use close to 80% of iptables proxier.go code, we should modularize it and re-factor the current implementation that our changes are minimum. 

Here are some example on how we could do that. 

Below Structres and their related methods are exactly same we should move them to a common source like util.go or something

```
type endpointsChange - All related functinos
type endpointsChangeMap - All related functions
type serviceChange  - All related functions
type serviceChangeMap - All related functions
type proxyServiceMap - All related functions
```

Belo functions are exactly same from iptables proxier and we should move them to a common file like Util.go

Below funcs are exactly same as iptables proxier.go
```
portOpener
writeLine
getNodeIPs
isLocalIP
openLocalPort
revertPorts
parseHostPort
shouldSkipService
endpointsToEndpointsMap
updateServiceMap
updateEndpointsMap
detectStaleConnections
```

Finally I think we should be able to EMBED iptable's proxier structure so that we only over-ride only those functions that are different from its original implementation.  Something like this?

```
The main strucutre has only two additional fields
type Proxier struct {
         iptables.Proxier     ///EMBED IPVS PROXIER structure
	 ipvs           utilipvs.Interface
	 ipvsScheduler  IpvsSchedulerType
} 
```
I believe by doing that ipvs's proxier.go implementation will drastically come down to 300-500 LOC and it will be much easier to get it reviewed from the community. 

Plus we don't have to take responsibility to re-cover already covered code in testing.  Apart from this i only see minor nits like adding more code comments about functions variables etc.,

**Comment by m1093782566** [comment]
@dhilipkumars 

I agree that reuse codes from iptables implementation is a good idea.However, my worry is that we need to refactor iptables proxy if we do that and will community accept the extra work? As you know, the modification can be large.

BTW, update the util functions that same as iptables proxier.go

portOpener
writeLine
isLocalIP
openLocalPort
revertPorts
shouldSkipService
endpointsToEndpointsMap
updateServiceMap
updateEndpointsMap
detectStaleConnections

getNodeIPs and parseHostPort are only used by ipvs proxy

Anyway, I will try to refactor step by step and to see the effect.

**Comment by dujun1990** [comment]
@dhilipkumars 

If we make a decision to refactor. I think maybe `pkg/proxy/util` is a dedicated package to place some of the important util functions. In my opinion, some funcs like `writeLine` are so simple that we no need to take effort to move them.


**pkg/proxy/util/port.go** for `portOpener` related functions.

```
openLocalPort
revertPorts
```

**pkg/proxy/util/endpoint.go** for the following functions.

```
endpointsToEndpointsMap
updateEndpointsMap
detectStaleConnections
```

**pkg/proxy/util/service.go** for the following functions.
```
updateServiceMap
```

**pkg/proxy/util/utils.go** for the following functions.

```
isLocalIP
shouldSkipService
```

**Comment by dhilipkumars** [comment]
I agree with the new files, we could also move out serviceInfo to utils as that is untouched aswell and used commonly by both these Proxier.  Also i take back my comment about Embedding iptables.Proxier structure into ipvs Proxier.  That wont work.

**Comment by dhilipkumars** [comment]
@m1093782566 Here is the little test i did the update did not disrupt the service or even the existing connection

```
sudo ipvsadm -L -n
[sudo] password for d:
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.11.12.13:6379 wlc persistent 10
  -> 10.192.0.1:32768             Masq    1      1          0
```
the real backedn service is redis-alpine conecting to the service
```
docker run --net=host -it redis:3.0-alpine redis-cli -h 10.11.12.13 -p 6379
10.11.12.13:6379> info Clients
# Clients
connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0
```
In a parllel session if i update the scheduler algorithm or persistence timeout the service is not disrupted.    Ipvsadm and libnetwor's ipvs pkg works in the same principle firing netlink message to the kernal so the behaviour should be the same.

Udpate persistance timout still no
```
$sudo ipvsadm -E -t 10.11.12.13:6379 -p 60
$sudo ipvsadm -L -n --persistent-conn
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port            Weight    PersistConn ActiveConn InActConn
  -> RemoteAddress:Port
TCP  10.11.12.13:6379 wlc persistent 60
  -> 10.192.0.1:32768             1         1           1          0
```

what other parameters should we test?

**Comment by m1093782566** [comment]
nice job! Thanks much.

**Pull request merged**
